import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import { Montserrat, Lalezar } from 'next/font/google'
import { ThemeProvider } from '@/context/ThemeContext'
const bodyFont = Montserrat({ subsets: ['latin'], weight: ['400', '700', '900'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyFont.className}>
        <ThemeProvider>
        <div className='container'>
          <Navbar />
          <div className='FullHeight'></div>
          {children}
          
          <Footer />
        </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
